spring:
  application:
    name: PaymentService
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: Consumer_PagFlow_Group
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      auto-offset-reset: earliest