spring:
  application:
    name: PaymentService
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: Consumer_PagFlow_Group
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      auto-offset-reset: earliest
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
flyway:
  enabled: true
  locations: classpath:db/migration
server:
  port: 8080
  error:
    include-message: always
    include-stacktrace: never
logging:
  level:
    org.hibernate.SQL: DEBUG
    org.springframework.kafka: INFO